### ISSUE TITLE
Make the home page responsive.

### ISSUE THREAD

**Issue by Mist12345** [autoNumeric/autonumeric.org#2]
See our conversation about this topic [here](https://github.com/autoNumeric/autonumeric.github.io/issues/2)

**Comment by Mist12345** [comment]
So, now I'm trying to commit my changes so I can create the pull request and I get this after I try `git add .` 
![image](https://user-images.githubusercontent.com/32372004/34062765-57e28be4-e1bc-11e7-8309-2e5ff73729a6.png)
I imagine this is why I had the issues in the beginning. I'm going to continue on and pretend like this shouldn't make a difference. If it does we'll deal with it then.

**Comment by AlexandreBonneau** [comment]
Fixed with PR #3
