### ISSUE TITLE
Setup https for autonumeric.org

### ISSUE THREAD

**Issue by tagliala** [autoNumeric/autonumeric.org#42]
Moved from autoNumeric/autoNumeric#775

Hello, there is a certificate issue when trying to access autonumeric.org

![image](https://github.com/autoNumeric/autoNumeric/assets/556268/53b0af40-aecc-48dd-a2e0-b8011e67355f)

---

Probably this can't be fixed by a PR, but I do have github pages on a custom domain and https works. At the moment I'm not confident to share details

Ref: https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

Could you please check if `/settings/pages` at https://github.com/autoNumeric/autonumeric.github.io is properly configured?

**Comment by AlexandreBonneau** [comment]
Ok, https is now live for https://autonumeric.org
